see #86: add support for reverse proxy headers
bitnami/bitnami-docker-wordpress-nginx pull request #87
Opened 2022-06-27 06:33 UTC by ziodave

**Description of the change**

Add support for reverse proxy headers in wp-config.php.

**Benefits**

Fixes #86 , allowing successful installation in environments where a reverse proxy is used.

**Possible drawbacks**

None.

**Applicable issues**

#86 

**Additional information**

2022-07-04 14:25 UTC, fmulero commented
Hi @ziodave, thanks a lot for your contribution

I've built your image and something seems wrong, I can not spin up a container from this code:
```
wordpress_1  | wordpress 14:10:57.69 INFO  ==> Installing WordPress
wordpress_1  | PHP Parse error:  syntax error, unexpected identifier "define" in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1277) : eval()'d code on line 170
```

You can reproduce the issue with the docker-compose provided in this repository

2022-07-05 06:21 UTC, ziodave commented
> Hi @ziodave, thanks a lot for your contribution
> 
> I've built your image and something seems wrong, I can not spin up a container from this code. This is the error:
> 
> ```
> wordpress_1  | wordpress 14:10:57.69 INFO  ==> Installing WordPress
> wordpress_1  | PHP Parse error:  syntax error, unexpected identifier "define" in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1277) : eval()'d code on line 170
> ```
> 
> You can reproduce the issue with the docker-compose provided in this repository

It's fixed (missing escapes).

2022-07-05 07:59 UTC, fmulero requested changes
Great contribution @ziodave, thanks a lot!!

I've checking the issue and possible scenarios and I agree this is the best solution. In my opinion this is a real/common scenario so I think other users sorted it out using rewriting rules, publishing wordpress internally over SSL or any other solution. Keeping in mind that and in order to avoid any collateral effect for those users, I think is worth to enable this feature using an ENV var keeping it disabled by default (to keep the current behaviour by default). What do you think? Could you apply those changes?

2022-07-05 08:55 UTC, ziodave commented
> Hi @ziodave, thanks a lot for your contribution
> 
> I've built your image and something seems wrong, I can not spin up a container from this code. This is the error:
> 
> ```
> wordpress_1  | wordpress 14:10:57.69 INFO  ==> Installing WordPress
> wordpress_1  | PHP Parse error:  syntax error, unexpected identifier "define" in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1277) : eval()'d code on line 170
> ```
> 
> You can reproduce the issue with the docker-compose provided in this repository

@fmulero it's implemented as a yes/no flag with name `WORDPRESS_ENABLE_REVERSE_PROXY`.

2022-07-07 16:57 UTC, fmulero requested changes
Great! I have only a little suggestion. If you are not able to do it, let us know, the rest looks really good. All tests passed in our side

2022-07-07 16:57 UTC, fmulero commented on README.md
> +- `WORDPRESS_ENABLE_REVERSE_PROXY`: Enable WordPress support for reverse proxy headers. Default: **no**
Could you move this line to the `User and Site configuration` section?

2022-07-11 08:10 UTC, fmulero approved these changes

2022-07-11 08:11 UTC, fmulero commented on README.md
> +- `WORDPRESS_ENABLE_REVERSE_PROXY`: Enable WordPress support for reverse proxy headers. Default: **no**
No problem, we could leave it as it is

2022-07-11 08:12 UTC, merged

2022-07-13 05:49 UTC, ziodave commented
> Great! I have only a little suggestion. If you are not able to do it, let us know, the rest looks really good. All tests passed in our side

sorry @fmulero I was ooo, just came back today. 🙏