see #83: check that wp-config.php exists in order to determine if WP …
bitnami/bitnami-docker-wordpress-nginx pull request #88
Opened 2022-06-27 06:43 UTC by ziodave

…is installed or not

**Description of the change**

Extend the check whether WordPress is already installed by looking for a `wp-config.php` file.

**Benefits**

Fixes a problem where the script would incorrectly assume WordPress is installed because the root folder exists. However the root folder may exists when users mount existing plugins or themes.

**Possible drawbacks**

None.

**Applicable issues**

#83 

**Additional information**

2022-06-28 08:24 UTC, javsalgar requested changes

2022-06-28 08:24 UTC, javsalgar commented on 5/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh
> +    if ! is_mounted_dir_empty "$persist_dir" && [[ -f "$persist_dir/wp-config.php" ]]; then
This function is used by all the application in the catalog, could you move the wp-config.php check to libwordpress.sh?

2022-06-29 06:51 UTC, ziodave commented on 5/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh
> +    if ! is_mounted_dir_empty "$persist_dir" && [[ -f "$persist_dir/wp-config.php" ]]; then
done

2022-06-30 11:23 UTC, javsalgar commented
Could you fix the merge issue?

2022-07-05 06:22 UTC, ziodave commented
> Could you fix the merge issue?

@javsalgar it's fixed.

2022-07-06 09:31 UTC, javsalgar approved these changes

2022-07-06 09:31 UTC, merged